export const SHOW_DATA = 'SHOW_DATA'
export const MOVE_LEFT = 'MOVE_LEFT'
export const MOVE_RIGHT = 'MOVE_RIGHT'
export const INIT_POS = 'INIT_POS'
export const IMPOSE_INDEX = 'IMPOSE_INDEX'
export const ON_SCROLLING  = 'ON_SCROLLING'